//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LambdaManager.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap _7 {
            get {
                object obj = ResourceManager.GetObject("7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 函数 的本地化字符串。
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 多次循环函数的输入数组长度不足 的本地化字符串。
        /// </summary>
        public static string ActionTimesInputCountNotMatch {
            get {
                return ResourceManager.GetString("ActionTimesInputCountNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 多次循环函数的输入数据不是数组类型 的本地化字符串。
        /// </summary>
        public static string ActionTimesInputTypeNotMatch {
            get {
                return ResourceManager.GetString("ActionTimesInputTypeNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数类型 的本地化字符串。
        /// </summary>
        public static string ArgType {
            get {
                return ResourceManager.GetString("ArgType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数 的本地化字符串。
        /// </summary>
        public static string Arguments {
            get {
                return ResourceManager.GetString("Arguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按指针类型处理 的本地化字符串。
        /// </summary>
        public static string AsPointer {
            get {
                return ResourceManager.GetString("AsPointer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 异步设置 的本地化字符串。
        /// </summary>
        public static string Async {
            get {
                return ResourceManager.GetString("Async", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持需要事件对象的情况 的本地化字符串。
        /// </summary>
        public static string AsyncWithEventDataNotSupport {
            get {
                return ResourceManager.GetString("AsyncWithEventDataNotSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持输出数据被引用的情况 的本地化字符串。
        /// </summary>
        public static string AsyncWithOutputReferredNotSupport {
            get {
                return ResourceManager.GetString("AsyncWithOutputReferredNotSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap backgroud {
            get {
                object obj = ResourceManager.GetObject("backgroud", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 类名称 的本地化字符串。
        /// </summary>
        public static string Class {
            get {
                return ResourceManager.GetString("Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应该使用类名称 的本地化字符串。
        /// </summary>
        public static string ClassNameWanted {
            get {
                return ResourceManager.GetString("ClassNameWanted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ： 的本地化字符串。
        /// </summary>
        public static string Comma {
            get {
                return ResourceManager.GetString("Comma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模块 的本地化字符串。
        /// </summary>
        public static string Component {
            get {
                return ResourceManager.GetString("Component", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应用组件加载完毕 的本地化字符串。
        /// </summary>
        public static string ConfigLoaded {
            get {
                return ResourceManager.GetString("ConfigLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始加载应用组件 的本地化字符串。
        /// </summary>
        public static string ConfigLoading {
            get {
                return ResourceManager.GetString("ConfigLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建失败 的本地化字符串。
        /// </summary>
        public static string CreateFailed {
            get {
                return ResourceManager.GetString("CreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap debug16 {
            get {
                object obj = ResourceManager.GetObject("debug16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 和其他库名相同但路径不一致，系统将加载其中一个库 的本地化字符串。
        /// </summary>
        public static string DuplicateLib {
            get {
                return ResourceManager.GetString("DuplicateLib", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 为空 的本地化字符串。
        /// </summary>
        public static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 接入点 的本地化字符串。
        /// </summary>
        public static string EntryPoint {
            get {
                return ResourceManager.GetString("EntryPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap error16 {
            get {
                object obj = ResourceManager.GetObject("error16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 不符合事件处理函数规范 的本地化字符串。
        /// </summary>
        public static string EventArgTypeNotMatch {
            get {
                return ResourceManager.GetString("EventArgTypeNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 事件传递的数据必须是JSON类型 的本地化字符串。
        /// </summary>
        public static string EventDataNotSupport {
            get {
                return ResourceManager.GetString("EventDataNotSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 事件类型未指定 的本地化字符串。
        /// </summary>
        public static string EventTypeNotSpecified {
            get {
                return ResourceManager.GetString("EventTypeNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行 的本地化字符串。
        /// </summary>
        public static string Execute {
            get {
                return ResourceManager.GetString("Execute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应用许可已过期，请联系厂家获得新的许可期限或者新的试用版本 的本地化字符串。
        /// </summary>
        public static string Expired {
            get {
                return ResourceManager.GetString("Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出 的本地化字符串。
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap fatal16 {
            get {
                object obj = ResourceManager.GetObject("fatal16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 文件 的本地化字符串。
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1 的本地化字符串。
        /// </summary>
        public static string FpsRunning {
            get {
                return ResourceManager.GetString("FpsRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入 的本地化字符串。
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap info16 {
            get {
                object obj = ResourceManager.GetObject("info16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 初始化 的本地化字符串。
        /// </summary>
        public static string Init {
            get {
                return ResourceManager.GetString("Init", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入参数类型 的本地化字符串。
        /// </summary>
        public static string InputType {
            get {
                return ResourceManager.GetString("InputType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 库 的本地化字符串。
        /// </summary>
        public static string Lib {
            get {
                return ResourceManager.GetString("Lib", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 菜单 的本地化字符串。
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称 的本地化字符串。
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不存在 的本地化字符串。
        /// </summary>
        public static string NotExist {
            get {
                return ResourceManager.GetString("NotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 函数不是调用有导出的流程 的本地化字符串。
        /// </summary>
        public static string NotExportProc {
            get {
                return ResourceManager.GetString("NotExportProc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未找到 的本地化字符串。
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提醒 的本地化字符串。
        /// </summary>
        public static string Notice {
            get {
                return ResourceManager.GetString("Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不匹配 的本地化字符串。
        /// </summary>
        public static string NotMatched {
            get {
                return ResourceManager.GetString("NotMatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持 的本地化字符串。
        /// </summary>
        public static string NotSupported {
            get {
                return ResourceManager.GetString("NotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 的 的本地化字符串。
        /// </summary>
        public static string of {
            get {
                return ResourceManager.GetString("of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开文件 的本地化字符串。
        /// </summary>
        public static string OpenFiles {
            get {
                return ResourceManager.GetString("OpenFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 或 的本地化字符串。
        /// </summary>
        public static string or {
            get {
                return ResourceManager.GetString("or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 和定义的输入参数不匹配 的本地化字符串。
        /// </summary>
        public static string OriginInputsNotMatch {
            get {
                return ResourceManager.GetString("OriginInputsNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输出参数类型 的本地化字符串。
        /// </summary>
        public static string OutputType {
            get {
                return ResourceManager.GetString("OutputType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请检查 的本地化字符串。
        /// </summary>
        public static string PleaseCheck {
            get {
                return ResourceManager.GetString("PleaseCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 流程 的本地化字符串。
        /// </summary>
        public static string Procedure {
            get {
                return ResourceManager.GetString("Procedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 触发事件键值 的本地化字符串。
        /// </summary>
        public static string RaiseKeys {
            get {
                return ResourceManager.GetString("RaiseKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 引用 的本地化字符串。
        /// </summary>
        public static string Reference {
            get {
                return ResourceManager.GetString("Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 引用的函数 的本地化字符串。
        /// </summary>
        public static string ReferredAction {
            get {
                return ResourceManager.GetString("ReferredAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 引用的输入数据未指定对应流程的函数参数位置 的本地化字符串。
        /// </summary>
        public static string ReferredArgsNotSpecified {
            get {
                return ResourceManager.GetString("ReferredArgsNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 引用 的本地化字符串。
        /// </summary>
        public static string Referring {
            get {
                return ResourceManager.GetString("Referring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 定时完成 的本地化字符串。
        /// </summary>
        public static string ScheduleEnd {
            get {
                return ResourceManager.GetString("ScheduleEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 定时执行 的本地化字符串。
        /// </summary>
        public static string ScheduleStart {
            get {
                return ResourceManager.GetString("ScheduleStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 定时触发 的本地化字符串。
        /// </summary>
        public static string ScheduleTrigger {
            get {
                return ResourceManager.GetString("ScheduleTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 签名 的本地化字符串。
        /// </summary>
        public static string Signature {
            get {
                return ResourceManager.GetString("Signature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应用启动时遇到严重错误，详细情况请查看日志： 的本地化字符串。
        /// </summary>
        public static string StartFatalError {
            get {
                return ResourceManager.GetString("StartFatalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap startpicture1 {
            get {
                object obj = ResourceManager.GetObject("startpicture1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap startpicture2 {
            get {
                object obj = ResourceManager.GetObject("startpicture2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 启动 的本地化字符串。
        /// </summary>
        public static string StartUp {
            get {
                return ResourceManager.GetString("StartUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 事件对象不支持二进制类型数据传递 的本地化字符串。
        /// </summary>
        public static string STLMapNotSupport {
            get {
                return ResourceManager.GetString("STLMapNotSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数个数大于4的函数不支持使用4字节以下的数据类型 的本地化字符串。
        /// </summary>
        public static string SystemNotSupport1 {
            get {
                return ResourceManager.GetString("SystemNotSupport1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数个数大于6的函数 的本地化字符串。
        /// </summary>
        public static string SystemNotSupport2 {
            get {
                return ResourceManager.GetString("SystemNotSupport2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未定义 的本地化字符串。
        /// </summary>
        public static string Undefined {
            get {
                return ResourceManager.GetString("Undefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap warning16 {
            get {
                object obj = ResourceManager.GetObject("warning16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
