//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LambdaCore {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LambdaCore.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Action 的本地化字符串。
        /// </summary>
        internal static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ActionTimesInputCountNotMatch 的本地化字符串。
        /// </summary>
        internal static string ActionTimesInputCountNotMatch {
            get {
                return ResourceManager.GetString("ActionTimesInputCountNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ActionTimesInputTypeNotMatch 的本地化字符串。
        /// </summary>
        internal static string ActionTimesInputTypeNotMatch {
            get {
                return ResourceManager.GetString("ActionTimesInputTypeNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ArgType 的本地化字符串。
        /// </summary>
        internal static string ArgType {
            get {
                return ResourceManager.GetString("ArgType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Arguments 的本地化字符串。
        /// </summary>
        internal static string Arguments {
            get {
                return ResourceManager.GetString("Arguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AsPointer 的本地化字符串。
        /// </summary>
        internal static string AsPointer {
            get {
                return ResourceManager.GetString("AsPointer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Async 的本地化字符串。
        /// </summary>
        internal static string Async {
            get {
                return ResourceManager.GetString("Async", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AsyncWithEventDataNotSupport 的本地化字符串。
        /// </summary>
        internal static string AsyncWithEventDataNotSupport {
            get {
                return ResourceManager.GetString("AsyncWithEventDataNotSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AsyncWithOutputReferredNotSupport 的本地化字符串。
        /// </summary>
        internal static string AsyncWithOutputReferredNotSupport {
            get {
                return ResourceManager.GetString("AsyncWithOutputReferredNotSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Class 的本地化字符串。
        /// </summary>
        internal static string Class {
            get {
                return ResourceManager.GetString("Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ClassNameWanted 的本地化字符串。
        /// </summary>
        internal static string ClassNameWanted {
            get {
                return ResourceManager.GetString("ClassNameWanted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ： 的本地化字符串。
        /// </summary>
        internal static string Comma {
            get {
                return ResourceManager.GetString("Comma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Component 的本地化字符串。
        /// </summary>
        internal static string Component {
            get {
                return ResourceManager.GetString("Component", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ConfigLoaded 的本地化字符串。
        /// </summary>
        internal static string ConfigLoaded {
            get {
                return ResourceManager.GetString("ConfigLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ConfigLoading 的本地化字符串。
        /// </summary>
        internal static string ConfigLoading {
            get {
                return ResourceManager.GetString("ConfigLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CreateFailed 的本地化字符串。
        /// </summary>
        internal static string CreateFailed {
            get {
                return ResourceManager.GetString("CreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DuplicateLib 的本地化字符串。
        /// </summary>
        internal static string DuplicateLib {
            get {
                return ResourceManager.GetString("DuplicateLib", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Empty 的本地化字符串。
        /// </summary>
        internal static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EntryPoint 的本地化字符串。
        /// </summary>
        internal static string EntryPoint {
            get {
                return ResourceManager.GetString("EntryPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EventArgTypeNotMatch 的本地化字符串。
        /// </summary>
        internal static string EventArgTypeNotMatch {
            get {
                return ResourceManager.GetString("EventArgTypeNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EventDataNotSupport 的本地化字符串。
        /// </summary>
        internal static string EventDataNotSupport {
            get {
                return ResourceManager.GetString("EventDataNotSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EventTypeNotSpecified 的本地化字符串。
        /// </summary>
        internal static string EventTypeNotSpecified {
            get {
                return ResourceManager.GetString("EventTypeNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Execute 的本地化字符串。
        /// </summary>
        internal static string Execute {
            get {
                return ResourceManager.GetString("Execute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expired 的本地化字符串。
        /// </summary>
        internal static string Expired {
            get {
                return ResourceManager.GetString("Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export 的本地化字符串。
        /// </summary>
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File 的本地化字符串。
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1 的本地化字符串。
        /// </summary>
        internal static string FpsRunning {
            get {
                return ResourceManager.GetString("FpsRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import 的本地化字符串。
        /// </summary>
        internal static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Init 的本地化字符串。
        /// </summary>
        internal static string Init {
            get {
                return ResourceManager.GetString("Init", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 InputType 的本地化字符串。
        /// </summary>
        internal static string InputType {
            get {
                return ResourceManager.GetString("InputType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lib 的本地化字符串。
        /// </summary>
        internal static string Lib {
            get {
                return ResourceManager.GetString("Lib", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Menu 的本地化字符串。
        /// </summary>
        internal static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NotExist 的本地化字符串。
        /// </summary>
        internal static string NotExist {
            get {
                return ResourceManager.GetString("NotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NotExportProc 的本地化字符串。
        /// </summary>
        internal static string NotExportProc {
            get {
                return ResourceManager.GetString("NotExportProc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NotFound 的本地化字符串。
        /// </summary>
        internal static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Notice 的本地化字符串。
        /// </summary>
        internal static string Notice {
            get {
                return ResourceManager.GetString("Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NotMatched 的本地化字符串。
        /// </summary>
        internal static string NotMatched {
            get {
                return ResourceManager.GetString("NotMatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NotSupported 的本地化字符串。
        /// </summary>
        internal static string NotSupported {
            get {
                return ResourceManager.GetString("NotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 of 的本地化字符串。
        /// </summary>
        internal static string of {
            get {
                return ResourceManager.GetString("of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OpenFiles 的本地化字符串。
        /// </summary>
        internal static string OpenFiles {
            get {
                return ResourceManager.GetString("OpenFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 or 的本地化字符串。
        /// </summary>
        internal static string or {
            get {
                return ResourceManager.GetString("or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OriginInputsNotMatch 的本地化字符串。
        /// </summary>
        internal static string OriginInputsNotMatch {
            get {
                return ResourceManager.GetString("OriginInputsNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OutputType 的本地化字符串。
        /// </summary>
        internal static string OutputType {
            get {
                return ResourceManager.GetString("OutputType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PleaseCheck 的本地化字符串。
        /// </summary>
        internal static string PleaseCheck {
            get {
                return ResourceManager.GetString("PleaseCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Procedure 的本地化字符串。
        /// </summary>
        internal static string Procedure {
            get {
                return ResourceManager.GetString("Procedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RaiseKeys 的本地化字符串。
        /// </summary>
        internal static string RaiseKeys {
            get {
                return ResourceManager.GetString("RaiseKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reference 的本地化字符串。
        /// </summary>
        internal static string Reference {
            get {
                return ResourceManager.GetString("Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ReferredAction 的本地化字符串。
        /// </summary>
        internal static string ReferredAction {
            get {
                return ResourceManager.GetString("ReferredAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ReferredArgsNotSpecified 的本地化字符串。
        /// </summary>
        internal static string ReferredArgsNotSpecified {
            get {
                return ResourceManager.GetString("ReferredArgsNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Referring 的本地化字符串。
        /// </summary>
        internal static string Referring {
            get {
                return ResourceManager.GetString("Referring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ScheduleEnd 的本地化字符串。
        /// </summary>
        internal static string ScheduleEnd {
            get {
                return ResourceManager.GetString("ScheduleEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ScheduleStart 的本地化字符串。
        /// </summary>
        internal static string ScheduleStart {
            get {
                return ResourceManager.GetString("ScheduleStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ScheduleTrigger 的本地化字符串。
        /// </summary>
        internal static string ScheduleTrigger {
            get {
                return ResourceManager.GetString("ScheduleTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Signature 的本地化字符串。
        /// </summary>
        internal static string Signature {
            get {
                return ResourceManager.GetString("Signature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 StartFatalError 的本地化字符串。
        /// </summary>
        internal static string StartFatalError {
            get {
                return ResourceManager.GetString("StartFatalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 StartUp 的本地化字符串。
        /// </summary>
        internal static string StartUp {
            get {
                return ResourceManager.GetString("StartUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 STLMapNotSupport 的本地化字符串。
        /// </summary>
        internal static string STLMapNotSupport {
            get {
                return ResourceManager.GetString("STLMapNotSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SystemNotSupport1 的本地化字符串。
        /// </summary>
        internal static string SystemNotSupport1 {
            get {
                return ResourceManager.GetString("SystemNotSupport1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SystemNotSupport2 的本地化字符串。
        /// </summary>
        internal static string SystemNotSupport2 {
            get {
                return ResourceManager.GetString("SystemNotSupport2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Undefined 的本地化字符串。
        /// </summary>
        internal static string Undefined {
            get {
                return ResourceManager.GetString("Undefined", resourceCulture);
            }
        }
    }
}
